//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLingo.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareLingo.Core.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string courseBrowser_cancelButtonText {
            get {
                return ResourceManager.GetString("courseBrowser_cancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course browser.
        /// </summary>
        public static string courseBrowser_header {
            get {
                return ResourceManager.GetString("courseBrowser_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string courseBrowser_saveButtonText {
            get {
                return ResourceManager.GetString("courseBrowser_saveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string courseEditor_courseAuthorHeader {
            get {
                return ResourceManager.GetString("courseEditor_courseAuthorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover.
        /// </summary>
        public static string courseEditor_courseCoverHeader {
            get {
                return ResourceManager.GetString("courseEditor_courseCoverHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string courseEditor_courseDocumentHeader {
            get {
                return ResourceManager.GetString("courseEditor_courseDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign.
        /// </summary>
        public static string courseEditor_courseForeignLanguageHeader {
            get {
                return ResourceManager.GetString("courseEditor_courseForeignLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string courseEditor_courseNameHeader {
            get {
                return ResourceManager.GetString("courseEditor_courseNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native language.
        /// </summary>
        public static string courseEditor_courseNativeLanguageHeader {
            get {
                return ResourceManager.GetString("courseEditor_courseNativeLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course&apos;s author must be specified..
        /// </summary>
        public static string courseEditor_error_emptyAuthorName {
            get {
                return ResourceManager.GetString("courseEditor_error_emptyAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course&apos;s name cannot be empty..
        /// </summary>
        public static string courseEditor_error_emptyCourseName {
            get {
                return ResourceManager.GetString("courseEditor_error_emptyCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course editor.
        /// </summary>
        public static string courseEditor_header {
            get {
                return ResourceManager.GetString("courseEditor_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        public static string courseNameValidator_nameCannotBeEmpty {
            get {
                return ResourceManager.GetString("courseNameValidator_nameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        public static string courseNameValidator_nameCannotContainIncorrectSymbols {
            get {
                return ResourceManager.GetString("courseNameValidator_nameCannotContainIncorrectSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error at canceling course changes..
        /// </summary>
        public static string log_error_courseEditor_cancelFailedUnhandled {
            get {
                return ResourceManager.GetString("log_error_courseEditor_cancelFailedUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error at deleting cover..
        /// </summary>
        public static string log_error_courseEditor_deleteCoverFailed {
            get {
                return ResourceManager.GetString("log_error_courseEditor_deleteCoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error at deleting document..
        /// </summary>
        public static string log_error_courseEditor_deleteDocumentFailed {
            get {
                return ResourceManager.GetString("log_error_courseEditor_deleteDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error at importing cover..
        /// </summary>
        public static string log_error_courseEditor_importCoverFailed {
            get {
                return ResourceManager.GetString("log_error_courseEditor_importCoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error at importing document..
        /// </summary>
        public static string log_error_courseEditor_importDocumentFailed {
            get {
                return ResourceManager.GetString("log_error_courseEditor_importDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error at saving course..
        /// </summary>
        public static string log_error_courseEditor_saveFailedUnhandled {
            get {
                return ResourceManager.GetString("log_error_courseEditor_saveFailedUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string mainWindow_courseBrowserNavigationMenuItem {
            get {
                return ResourceManager.GetString("mainWindow_courseBrowserNavigationMenuItem", resourceCulture);
            }
        }
    }
}
