//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLingo.WinUI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareLingo.WinUI.Resources.Strings.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string courseBrowser_header {
            get {
                return ResourceManager.GetString("courseBrowser_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string courseBrowser_header1 {
            get {
                return ResourceManager.GetString("courseBrowser_header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string courseNameValidator_nameCannotBeEmpty {
            get {
                return ResourceManager.GetString("courseNameValidator_nameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string courseNameValidator_nameCannotBeEmpty1 {
            get {
                return ResourceManager.GetString("courseNameValidator_nameCannotBeEmpty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A course name cannot contain such characters..
        /// </summary>
        public static string courseNameValidator_nameCannotContainIncorrectSymbols {
            get {
                return ResourceManager.GetString("courseNameValidator_nameCannotContainIncorrectSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A course name cannot contain such characters..
        /// </summary>
        public static string courseNameValidator_nameCannotContainIncorrectSymbols1 {
            get {
                return ResourceManager.GetString("courseNameValidator_nameCannotContainIncorrectSymbols1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dlgGen_cancelButtonText {
            get {
                return ResourceManager.GetString("dlgGen_cancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dlgGen_cancelButtonText1 {
            get {
                return ResourceManager.GetString("dlgGen_cancelButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string dlgGen_noButtonText {
            get {
                return ResourceManager.GetString("dlgGen_noButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string dlgGen_noButtonText1 {
            get {
                return ResourceManager.GetString("dlgGen_noButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string dlgGen_okButtonText {
            get {
                return ResourceManager.GetString("dlgGen_okButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string dlgGen_okButtonText1 {
            get {
                return ResourceManager.GetString("dlgGen_okButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string dlgGen_yesButtonText {
            get {
                return ResourceManager.GetString("dlgGen_yesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string dlgGen_yesButtonText1 {
            get {
                return ResourceManager.GetString("dlgGen_yesButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string mainWindow_courseBrowserNavigationMenuItem {
            get {
                return ResourceManager.GetString("mainWindow_courseBrowserNavigationMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string mainWindow_courseBrowserNavigationMenuItem1 {
            get {
                return ResourceManager.GetString("mainWindow_courseBrowserNavigationMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string promptDialog_textInvalidTItle {
            get {
                return ResourceManager.GetString("promptDialog_textInvalidTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string promptDialog_textInvalidTItle1 {
            get {
                return ResourceManager.GetString("promptDialog_textInvalidTItle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided name is acceptable.
        /// </summary>
        public static string promptDialog_textValidTitle {
            get {
                return ResourceManager.GetString("promptDialog_textValidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided name is acceptable.
        /// </summary>
        public static string promptDialog_textValidTitle1 {
            get {
                return ResourceManager.GetString("promptDialog_textValidTitle1", resourceCulture);
            }
        }
    }
}
