//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLingo.WinUI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShareLingo.WinUI.Resources.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this course? This action cannot be undo..
        /// </summary>
        internal static string courseBrowser_deleteSelectedCourseConfirm {
            get {
                return ResourceManager.GetString("courseBrowser_deleteSelectedCourseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the course&apos;s name:.
        /// </summary>
        internal static string courseBrowser_enterCourseNamePrompt {
            get {
                return ResourceManager.GetString("courseBrowser_enterCourseNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided course name is already in use..
        /// </summary>
        internal static string courseBrowser_enteredCourseNameAlreadyInUseError {
            get {
                return ResourceManager.GetString("courseBrowser_enteredCourseNameAlreadyInUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided course name is already in use..
        /// </summary>
        internal static string courseInspector_enteredCourseNameAlreadyInUse {
            get {
                return ResourceManager.GetString("courseInspector_enteredCourseNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong course name..
        /// </summary>
        internal static string courseInspector_enteredCourseNameWrong {
            get {
                return ResourceManager.GetString("courseInspector_enteredCourseNameWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered foreign language is wrong..
        /// </summary>
        internal static string courseInspector_enteredForeignLanguageWrong {
            get {
                return ResourceManager.GetString("courseInspector_enteredForeignLanguageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong module name..
        /// </summary>
        internal static string courseInspector_enteredModuleNameAlreadyInUse {
            get {
                return ResourceManager.GetString("courseInspector_enteredModuleNameAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered native language is wrong..
        /// </summary>
        internal static string courseInspector_enteredNativeLanguageWrong {
            get {
                return ResourceManager.GetString("courseInspector_enteredNativeLanguageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the module&apos;s name:.
        /// </summary>
        internal static string courseInspector_enterModuleNamePrompt {
            get {
                return ResourceManager.GetString("courseInspector_enterModuleNamePrompt", resourceCulture);
            }
        }
    }
}
